[package]
name = "too_many_lists"
version = "0.1.0"
authors = ["Caleb Garrick <caleb.garrick@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
